### PR TITLE
update contributing

### LINKED ISSUE #38: Include some workflow commands in Contributing.md
Some that I have been using:

`cabal-docspec --check-properties`
`cabal v2-test --enable-coverage`

Nothing too crazy. Might be good to add a "contributor's check" script?

This is very low priority.

### PR DESCRIPTION
**Pull request by santiweight**

### CODE REVIEW

**Comment by santiweight** [comment]
@tonyday567 This will be of interest to you i think

**Review by tonyday567 — COMMENTED** [review]
I tend to drop the v2- stuff in the hope that we will stop living in the past.

LGTM

**Comment by santiweight** [comment]
Sadly it will do weird stuff iirc with docspec

**Comment by santiweight** [comment]
`build` is different from `v2-build` still right?

**Comment by tonyday567** [comment]
> build is different from v2-build still right?

Don't quote me, but i think v2-build and build are the same thing for a modern cabal executable

**Pull request merged**
